# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: SonatypeEvaluate@0
  name: sonatypePolicyEvaluation
  inputs:
    cliVersion: '2.1.1'
    nexusIqService: 'Sonatype IQ Server'
    applicationId: 'sandbox-application'
    stage: 'Build'
    scanTargets: '**/pom.xml'
    acceptIqServerSelfSignedCertificates: true

- task: SonatypeFetchSbom@0
  name: sonatypeFetchSbomTask
  displayName: 'Sonatype IQ Fetch SBOM'
  inputs:
    nexusIqService: 'Sonatype IQ Server'
    applicationId: 'sandbox-application'
    scanId: 'sonatypePolicyEvaluation.scanId'
    sbomStandard: 'cyclonedx'
    sbomVersion: '1.6'
    acceptIqServerSelfSignedCertificates: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'sbom.zip'
    publishLocation: 'pipeline'
    
- task: NexusIqPipelineTask@0
  inputs:
    nexusIqService: 'Sonatype IQ Server'
    applicationId: 'aa-1'
    stage: 'Build'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
